version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: clinica_postgres
    environment:
      POSTGRES_DB: clinica_estetica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=200'

volumes:
  postgres_data: